import { Geist, Geist_Mono } from "next/font/google"

import type { Metadata } from "next"

import "./globals.css"

import Footer from "@/_components/Footer"
import { ArticleSearchProvider } from "@/context/articleContext"

import Header from "../_components/Header"
import Hero_Section from "../_components/Hero_Section"
import { NavProvider } from "../context/NavContext"

// import { FormSearchProvider } from "@/context/FormSearchContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ArticleSearchProvider>
          <NavProvider>
            <Header />
            {children}
            <Footer />
          </NavProvider>
        </ArticleSearchProvider>
      </body>
    </html>
  )
}
